### ISSUE TITLE
Make outfits craftable

### ISSUE THREAD

**Issue by bp88dev** [KViEternal/Combat_Maid_Mod#1]
Currently, I can't find a way to craft the outfits in survival Minecraft. I wanted to add this mod to a survival server I have with friends but it's unclear how to obtain them.

**Comment by KViEternal** [comment]
You can find the current crafting recipes [here](https://wiki.kvieternal.com/combat-maids-mod/). If you have any suggestions for changes or new features to add, I would greatly appreciate hearing them.

**Comment by hakanai** [comment]
The recipes don't show up in the JEI index. But once you have crafted the item, the recipes show in JEI fine and can even be bookmarked.

**Comment by KViEternal** [comment]
Thank you for bringing this to my attention! Please keep an eye out for the upcoming update, which should resolve this issue.

> The recipes don't show up in the JEI index. But once you have crafted the item, the recipes show in JEI fine and can even be bookmarked.
